### ISSUE TITLE
how to configure http proxy with user and passsword?

### ISSUE THREAD

**Issue by zhongxiaoma** [crops/chameleonsocks#8]
Hi:
    I'm trying to get this working as part of the Yocto build system on Ubuntu Server 16.04.1 with HTTP proxy.  

   from README file , i don't see any description how to configure proxy user and passwd, such as for genereal http_proxy which need indicate user and passwd:
    export http_proxy='http://user:passwd@proxy.xxxx.com:8080/'

 so, i follow the previous pattern, modify like this:
 : ${PROXY:=user:passwd@proxy.xxxx.com}
: ${PORT:=8080}
: ${PROXY_TYPE:=http-connect}

after this configure, git command also failed,
 git ls-remote https://github.com/msgpack/msgpack-c.git
fatal: unable to access 'https://github.com/msgpack/msgpack-c.git/': Failed to connect to github.com port 443: Connection refused

please give me some advice ,thanks alot

**Comment by todorez** [comment]
Hello,

At the moment you cannot set the username/password in the PROXY variable.

- The way to get around this is will be to set PROXY:=proxy.xxxx.com.

- Run the install script (chameleonsocks.sh --install)

- Get a shell in the container (docker exec -ti chameleonsocks bash)

- Add your login details to /etc/redsocks.conf

Example : 
redsocks {
	local_ip = 0.0.0.0;
	local_port = 1080;
	ip = proxy.xxx.com;
	port = 8080;
	type = http-connect;
        login = "your_username";
        password = "your_password";
}

- Restart chameleonsocks 
./chameleonsocks.sh --stop
./chameleonsocks.sh --start

This should do it. 
I will add PASSWORD authentication as soon as I have a bit a free time.
